peers: []

http:
  external:
    listen_address: 0.0.0.0
    port: 3013
  internal:
    listen_address: 0.0.0.0
    port: 3113
    debug_endpoints: true

chain:
  persist: true
  protocol_beneficiaries: ["ak_pQbLq4uSsipYKzg2DUnMJamHnPYrdrbgtR7wXe6iLLARyhHKy:109"]
  hard_forks:
    "1": 0
    "2": 2
    "3": 4
    "4": 6

mempool:
  nonce_offset: 1000

mining:
  autostart: true
  beneficiary: "ak_pQbLq4uSsipYKzg2DUnMJamHnPYrdrbgtR7wXe6iLLARyhHKy"
  expected_mine_rate: 4000
  micro_block_cycle: 1000
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      edge_bits: 15
      # nice: 3

fork_management:
  network_id: "ae_devnet"
